### ISSUE TITLE
May be ml_collections issue

### ISSUE THREAD

**Issue by adhikarirsr** [google-deepmind/digraph_transformer#4]
```
python experiment.py --jaxline_mode=train --config=./config.py:norevogb,bignn,maglappos,bbs --config.experiment_kwargs.config.data.root=./data_new --config.random_seed=1000 --config.checkpoint_dir=./ckpt2
```

`./data_new` has files downloaded from the google drive. `data _new `has a folder named `ogbg-code2-norev-df `with `train`, `valid`, and `test`. 

throws following error:
```
/site-packages/ml_collections/config_dict/config_dict.py", line 903, in __getitem__
    field = self._fields[key]
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/digraph_transformer/experiment.py", line 727, in <module>
    app.run(lambda argv: main(argv, Experiment))
  File "~/.conda/envs/digt/lib/python3.10/site-packages/absl/app.py", line 300, in run
    args = _run_init(
  File "~/.conda/envs/digt/lib/python3.10/site-packages/absl/app.py", line 369, in _run_init
    args = _register_and_parse_flags_with_usage(
  File "~/.conda/envs/digt/lib/python3.10/site-packages/absl/app.py", line 216, in _register_and_parse_flags_with_usage
    args_to_main = flags_parser(original_argv)
  File "~/.conda/envs/digt/lib/python3.10/site-packages/absl/app.py", line 156, in parse_flags_with_usage
    return FLAGS(args)
  File "~/.conda/envs/digt/lib/python3.10/site-packages/absl/flags/_flagvalues.py", line 646, in __call__
    unknown_flags, unparsed_args = self._parse_args(args, known_only)
  File "~/.conda/envs/digt/lib/python3.10/site-packages/absl/flags/_flagvalues.py", line 796, in _parse_args
    flag.parse(value)
  File "~/.conda/envs/digt/lib/python3.10/site-packages/absl/flags/_flag.py", line 168, in parse
    self.value = self._parse(argument)
  File "~/.conda/envs/digt/lib/python3.10/site-packages/ml_collections/config_flags/config_flags.py", line 625, in _parse
    overrides_types = GetTypes(overrides, config)
  File "~/.conda/envs/digt/lib/python3.10/site-packages/ml_collections/config_flags/config_flags.py", line 911, in GetTypes
    return [GetType(path, config) for path in paths]
  File "~/.conda/envs/digt/lib/python3.10/site-packages/ml_collections/config_flags/config_flags.py", line 911, in <listcomp>
    return [GetType(path, config) for path in paths]
  File "~/.conda/envs/digt/lib/python3.10/site-packages/ml_collections/config_flags/config_flags.py", line 892, in GetType
    current = _TakeStep(current, step)
  File "~/.conda/envs/digt/lib/python3.10/site-packages/ml_collections/config_flags/config_flags.py", line 876, in _TakeStep
    return _AccessConfig(current, field, indices)
  File "~/.conda/envs/digt/lib/python3.10/site-packages/ml_collections/config_flags/config_flags.py", line 852, in _AccessConfig
    current = current[field]
  File "~/.conda/envs/digt/lib/python3.10/site-packages/ml_collections/config_dict/config_dict.py", line 909, in __getitem__
    raise KeyError(self._generate_did_you_mean_message(key, str(e)))
KeyError: "'data'"

```
Testing trained model from the google drive:
```
python ./experiment.py --jaxline_mode="eval"  --config="./config.py:dfogb,bignn,maglappos,bbs"   --config.restore_path=./ogb_models/step_100176_2023-05-29T16\:59\:17/    --config.experiment_kwargs.config.data_root=./data_new
```
works fine! `ogb_models` has trained models downloaded from the google drive

**Comment by adhikarirsr** [comment]
Found an error in my command. Sorry about it.

`data_root` instead of `data.root`
